spring:
  h2:
    console:
      enabled: true
      path: /console
  thymeleaf:
    cache: false
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 706937288830-3v9t7o7qu58umctpvl6a8at0euig9n9j.apps.googleusercontent.com
            client-secret: t7tJpMABddmCfOdilFUuTlbq
            #facebook:
            #client-id: 11612612521462
            #client-secret: 6578235217c5c365a98c51b02d0308ac
custom:
  oauth2:
    kakao:
      client-id: dcd9b2e7423ad56c21110b034982d24f
      client-secret: QkIf3kz8q1fwZIFrqjjuai9O2Lfnfhgs
    naver:
      client-id: tw8_wYg4GXjuAj8hWhB9
      client-secret: eYJwbyWbYZ